### ISSUE TITLE
Consistent Competitors ID

### ISSUE THREAD

**Issue by hexIV** [rivalrygg/rivalry-api#11]
In each match, there are 2 `competitors` and each team has an ID and a name associated with them. The ID for some reason is not the same for a team playing multiple matches. For example right now Acend shows up in 2 VALORANT matches . In one match the ID is 524622 while in the other match it's 547182. How possible is it for the Acend team to get a consistent ID associated with it?

This change would help us do auto-matching between your teams and our teams in the DB.

**Comment by ryantology** [comment]
You are correct, the `acend` competitor is duplicated nearly 70 times in our database over the past year. As a bit of background, we used to spend a lot of time and resources trying to alias competitors and ensure that they are in the database once and can be easily cross referenced.

This was an extreme amount of work and we generally were never 100% perfect on this. We have since given up on ensuring that `Acend` is only a single valorant competitor. Sometimes the roster changes or the team re-names but the roster is the same. Sometimes we need to know that the team had an alternate name at a specific point in time for auditing. All of these edge cases made it untenable to continue the aliasing tasks.

I wish we had a better answer for you on this but it's just not something we are able to make work at this time.
